# Generated by Django 3.1.7 on 2021-04-28 17:06

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avlShifts',
            fields=[
                ('shift_ID', models.AutoField(primary_key=True, serialize=False)),
                ('shift_Time', models.CharField(max_length=11)),
                ('shift_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='penShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
                ('store_Number', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('store_Name', models.CharField(max_length=30)),
                ('store_address', models.CharField(max_length=30)),
                ('store_Contact', phone_field.models.PhoneField(help_text='Contact number for store', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='wrkShifts',
            fields=[
                ('confimation_number', models.AutoField(primary_key=True, serialize=False)),
                ('shift_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.avlshifts')),
            ],
        ),
    ]
